### ISSUE TITLE
Adding A1 Devices cause failure

### ISSUE THREAD

**Issue by ondrovic** [davglass/bambu-farm#2]
```log
{
app/node_modules/basic-ftp/dist/FtpContext.js:283
             const err = code >= 400 ? new FTPError(response) : undefined;
                                       ^

FTPError: 550 
 at FTPContext._onControlSocketData (/app/node_modules/basic-ftp/dist/FtpContext.js:283:39)
 at TLSSocket.<anonymous> (/app/node_modules/basic-ftp/dist/FtpContext.js:127:44)
at TLSSocket.emit (node:events:514:28)
at addChunk (node:internal/streams/readable:545:12)
 at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
at Readable.push (node:internal/streams/readable:375:5)
at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
 code: 550
}
```

When adding in A1 Mini the above cause the app to crash, removing and having just my X1C app works correctly

**Comment by davglass** [comment]
I don't have direct access to an `A` model to test with, I have a friend with one that I may be able to test with.
