### ISSUE TITLE
Error in App Container on Startup

### ISSUE THREAD

**Issue by Locxion** [davglass/bambu-farm#5]
Iam getting this error on Startup of the App Container
`2024-09-29 20:33:05 /app/node_modules/basic-ftp/dist/FtpContext.js:283
2024-09-29 20:33:05             const err = code >= 400 ? new FTPError(response) : undefined;
2024-09-29 20:33:05                                       ^
2024-09-29 20:33:05 
2024-09-29 20:33:05 FTPError: 550 Failed to change directory.
2024-09-29 20:33:05     at FTPContext._onControlSocketData (/app/node_modules/basic-ftp/dist/FtpContext.js:283:39)
2024-09-29 20:33:05     at TLSSocket.<anonymous> (/app/node_modules/basic-ftp/dist/FtpContext.js:127:44)
2024-09-29 20:33:05     at TLSSocket.emit (node:events:519:28)
2024-09-29 20:33:05     at addChunk (node:internal/streams/readable:559:12)
2024-09-29 20:33:05     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
2024-09-29 20:33:05     at Readable.push (node:internal/streams/readable:390:5)
2024-09-29 20:33:05     at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23) {
2024-09-29 20:33:05   code: 550
2024-09-29 20:33:05 }
2024-09-29 20:33:05 
2024-09-29 20:33:05 Node.js v20.15.0`

**Comment by Locxion** [comment]
Anyone able to help with this?
